### ISSUE TITLE
Minimal Documentation

### ISSUE THREAD

**Issue by s0undt3ch** [fantix/aiocontextvars#1]
It would be useful to at least have some minimal usage examples in the read me file. Of course, documentation would even be better.

**Comment by fantix** [comment]
Yes definitely! We are working on it. Thanks for the issue 😃

**Comment by fantix** [comment]
Fixed! Please see latest README

**Comment by s0undt3ch** [comment]
Superb! Thanks!

**Comment by fantix** [comment]
😺  pleasure
