### ISSUE TITLE
Is uvloop compatible with this library?

### ISSUE THREAD

**Issue by bmintz** [fantix/aiocontextvars#14]
"Because above hack is done by replacing asyncio.get_event_loop and loop.create_task, therefore tasks and loops created by custom/private API won't behave correctly as expected, e.g. uvloop.new_event_loop() or asyncio.Task(). Also, event loops created before importing aiocontextvars are not patched either. So over all, you should import aiocontextvars at the beginning before creating event loops, and always use asyncio.* to operate loops/policies, and public asyncio API to create tasks."

Does this mean I can't use uvloop at all, or just don't use the uvloop.new_event_loop()?

**Comment by bmintz** [comment]
Duplicate of #

**Comment by fantix** [comment]
Just don't use the `uvloop.new_event_loop()` :) Use this:

```
import asyncio
import uvloop
asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
```

And get your event loops through `asyncio.get_event_loop()` and friends.

**Comment by bmintz** [comment]
OK, thank you.
